export type Language = 'ja' | 'en'

export const copy = {
  ja: {
    body: '本文', hint: '文章を貼り付けるか、ここに入力してください。', direction: '読み方向', vertical: '縦書き', horizontal: '横書き', paper: '用紙サイズ', paperOrientation: '紙の向き', portrait: '縦向き', landscape: '横向き', composition: '文字数と行数', details: '詳細設定（任意）', fontFamily: 'フォントの種類', mincho: '明朝体', gothic: 'ゴシック体', fontSize: '文字サイズ', medium: '中', margin: '余白', marginNarrow: '狭め', marginWidePrint: '広め（印刷が切れる場合）', gridColor: '罫線の色', paragraphIndent: '段落を自動適用', serviceMark: '紙面左下に kantan.snkisk.com を入れる', preview: '仕上がりプレビュー', blank: '文章を貼り付けてください', save: 'PDFとして保存', saving: 'PDFを準備中…', print: '印刷する', printing: '印刷を開いています…', printReady: '印刷メニューを開きました。', pdfReady: 'PDFを保存しました。', pdfError: 'PDFを保存できませんでした。もう一度試してください。', retry: 'もう一度試す', info: '設定の説明', settingsInfo: '用紙、読み方向、文字数と行数で仕上がりを確認できます。細かな調整は必要な時だけ開けます。', sourceCount: '本文', sourceSuffix: '文字', page: 'ページ', appearance: '見た目', language: '言語', japanese: '日本語', english: 'English', system: 'システム', light: 'ライト', dark: 'ダーク', pages: 'ページ', close: '閉じる', characters: '字', lines: '行', small: '小', standard: '標準', large: '大', serviceName: 'kantan.snkisk.com', copyright: '© 2026 新快速(Special-Rapid)', contact: 'contact@snkisk.com'
  },
  en: {
    body: 'Text', hint: 'Paste or write your text here.', direction: 'Writing direction', vertical: 'Vertical', horizontal: 'Horizontal', paper: 'Paper size', paperOrientation: 'Paper orientation', portrait: 'Portrait', landscape: 'Landscape', composition: 'Characters and lines', details: 'Optional settings', fontFamily: 'Font family', mincho: 'Mincho', gothic: 'Gothic', fontSize: 'Text size', medium: 'Medium', margin: 'Margins', marginNarrow: 'Narrow', marginWidePrint: 'Wide (for printer margins)', gridColor: 'Grid color', paragraphIndent: 'Apply paragraph indents', serviceMark: 'Add kantan.snkisk.com at the lower left', preview: 'Layout preview', blank: 'Paste your text to begin', save: 'Save as PDF', saving: 'Preparing PDF…', print: 'Print', printing: 'Opening print…', printReady: 'Print dialog opened.', pdfReady: 'PDF saved.', pdfError: 'PDF could not be saved. Please try again.', retry: 'Try again', info: 'About settings', settingsInfo: 'Choose paper, direction, and a character/line layout. Open the optional settings only when you need finer control.', sourceCount: 'Text', sourceSuffix: 'characters', page: 'Page', appearance: 'Appearance', language: 'Language', japanese: 'Japanese', english: 'English', system: 'System', light: 'Light', dark: 'Dark', pages: 'pages', close: 'Close', characters: 'characters', lines: 'lines', small: 'Small', standard: 'Standard', large: 'Large', serviceName: 'kantan.snkisk.com', copyright: '© 2026 新快速(Special-Rapid)', contact: 'contact@snkisk.com'
  },
} as const

export type Labels = Record<keyof typeof copy.ja, string>
